install: ant resolve-deps
language: scala
jdk:
  - oraclejdk7
  - openjdk7
scala:
  - 2.10.1
script: ant run-junit
before_script:
  - export JAVA_OPTS="-Xmx2048M -XX:MaxPermSize=1024M -XX:+CMSClassUnloadingEnabled -XX:+UseConcMarkSweepGC"
